apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: k8s.gcr.io/busybox
    command: [ "/bin/sh", "-c", "ls /etc/foo && sleep 3600" ]
    volumeMounts:
    - name: secret-volume
      mountPath: "/etc/foo"
  volumes:
  - name: secret-volume
    secret:
      secretName: mysecret
      items:
      - key: password
        path: password
