apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "YOUR_MANAGED_IDENTITY_ID"
    keyvaultName: "NAME_OF_YOUR_KEY_VAULT"
    cloudName: ""
    cloudEnvFileName: ""
    objects: |
      array:
        - |
          objectName: NAME_OF_YOUR_SECRET
          objectAlias: SECRET_1
          objectType: secret
          objectVersion: ""
    tenantId: "YOUR_TENANT_ID"