apiVersion: v1
kind: Pod
metadata:
  name: nginx-prod
  labels:
    app: myapp
    tier: frontend
    version: 1.0.0
    environment: production
spec:
  containers:
  - name: myapp-container
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
  labels:
    app: myapp
    tier: frontend
    version: 1.1.0
    environment: test
spec:
  containers:
  - name: myapp-container
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-dev
  labels:
    app: myapp
    tier: frontend
    version: 1.2.0
    environment: dev
spec:
  containers:
  - name: myapp-container
    image: nginx
    ports:
    - containerPort: 80