apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: my-config-map-4
              key: special.how
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: my-config-map-5
              key: log_level
  restartPolicy: Never