apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config-map-4
  namespace: default
data:
  special.how: very
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config-map-5
  namespace: default
data:
  log_level: INFO